spring:
  application:
    #应用名称
    name: service-graytest

  redis:
    database: 0
    host: 192.168.1.8
    port: 6379
    password:
    #连接超时时间
    timeout: 5000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
    #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30


---
spring:
  profiles: v1

eureka:
  instance:
    metadata-map:
      version: v1
      a: a1
server:
  #服务端口
  port: 8001
---
spring:
  profiles: v2

eureka:
  instance:
    metadata-map:
      version: v2
server:
  #服务端口
  port: 8002
